"""
QA companion script for the FY26/FY27 Connecticut budget extraction.

This utility inspects the SQLite tables produced by `rebuild_budget_from_pdf.py`
and emits reconciliation metrics plus CSV exports that highlight gaps between
agency detail totals and the subcommittee summary tables.
"""

from __future__ import annotations

import argparse
import json
import sqlite3
from pathlib import Path
from typing import Dict, List

import pandas as pd

AGENCY_WIDE_TABLE = "budget_agency_accounts_wide"
AGENCY_LONG_TABLE = "budget_agency_accounts_long"
POLICY_TABLE = "budget_policy_changes"
SUBCOMMITTEE_TABLE = "budget_subcommittee_summary"


def ensure_output_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def load_table(conn: sqlite3.Connection, table: str) -> pd.DataFrame:
    return pd.read_sql_query(f"SELECT * FROM {table}", conn)


def scenario_columns(df: pd.DataFrame) -> List[str]:
    columns = [
        "actual_fy23",
        "actual_fy24",
        "appropriation_fy25",
        "governor_fy26",
        "governor_fy27",
        "legislative_fy26",
        "legislative_fy27",
    ]
    return [col for col in columns if col in df.columns]


def summarize_tables(
    wide_df: pd.DataFrame,
    long_df: pd.DataFrame,
    policy_df: pd.DataFrame,
    subcommittee_df: pd.DataFrame,
) -> Dict[str, int]:
    summary = {
        "wide_rows": len(wide_df),
        "long_rows": len(long_df),
        "policy_rows": len(policy_df),
        "subcommittee_rows": len(subcommittee_df),
        "agencies": wide_df["agency"].nunique() if not wide_df.empty else 0,
        "funds": wide_df["fund"].nunique() if not wide_df.empty else 0,
        "accounts": wide_df["account"].nunique() if not wide_df.empty else 0,
    }
    return summary


def reconcile_totals(
    wide_df: pd.DataFrame,
    subcommittee_df: pd.DataFrame,
) -> pd.DataFrame:
    if wide_df.empty or subcommittee_df.empty:
        return pd.DataFrame()

    scenario_cols = scenario_columns(wide_df)
    agency_totals = (
        wide_df[wide_df["row_type"] == "fund_total"]
        .groupby(["subcommittee", "agency", "fund"], dropna=False)[scenario_cols]
        .sum()
        .reset_index()
    )

    subcommittee_totals = (
        subcommittee_df[subcommittee_df["row_type"] != "agency_total"]
        .groupby(["subcommittee", "agency", "fund"], dropna=False)[scenario_cols]
        .sum()
        .reset_index()
    )

    reconciliation = pd.merge(
        agency_totals,
        subcommittee_totals,
        on=["subcommittee", "agency", "fund"],
        how="outer",
        suffixes=("_agency", "_subcommittee"),
    )

    for col in scenario_cols:
        reconciliation[f"{col}_diff"] = (
            reconciliation[f"{col}_agency"].fillna(0)
            - reconciliation[f"{col}_subcommittee"].fillna(0)
        )
    return reconciliation


def policy_span_report(policy_df: pd.DataFrame) -> pd.DataFrame:
    if policy_df.empty:
        return pd.DataFrame()
    fields = [
        "source_document",
        "subcommittee",
        "agency",
        "policy_title",
        "page_start",
        "page_end",
        "fund",
    ]
    return policy_df[fields].drop_duplicates()


def run_qa(db_path: Path, output_dir: Path) -> None:
    ensure_output_dir(output_dir)
    with sqlite3.connect(db_path) as conn:
        wide_df = load_table(conn, AGENCY_WIDE_TABLE)
        long_df = load_table(conn, AGENCY_LONG_TABLE)
        policy_df = load_table(conn, POLICY_TABLE)
        subcommittee_df = load_table(conn, SUBCOMMITTEE_TABLE)

    summary = summarize_tables(wide_df, long_df, policy_df, subcommittee_df)
    (output_dir / "qa_summary.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8"
    )

    reconciliation = reconcile_totals(wide_df, subcommittee_df)
    if not reconciliation.empty:
        reconciliation.to_csv(output_dir / "reconciliation_details.csv", index=False)

    policy_span_df = policy_span_report(policy_df)
    if not policy_span_df.empty:
        policy_span_df.to_csv(output_dir / "policy_page_spans.csv", index=False)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="QA the FY26/FY27 Connecticut budget extraction output."
    )
    parser.add_argument(
        "--db-path",
        type=Path,
        required=True,
        help="SQLite DB path generated by rebuild_budget_from_pdf.py",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("qa_outputs"),
        help="Directory for QA CSV/JSON artifacts.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    run_qa(args.db_path, args.output_dir)


if __name__ == "__main__":
    main()
